import type { Project } from '../schema'

export const berineMetabolic: Project = {
  slug: 'berine-metabolic',
  title: 'Berine Metabolic',
  subtitle: 'Clinical diabetes education, online',
  summary:
    'An online course for adults with type 2 diabetes and the platform behind it: site, course app, payments and a pipeline that produces 120+ lesson videos.',
  body: [
    'Berine Metabolic makes clinical diabetes education available to anyone, starting with an online course for adults with type 2 diabetes.',
    'I lead product and engineering across the full platform, from the website and course app to payments, a clinical review desk and the pipeline that renders every lesson video.',
    {
      kind: 'flow',
      title: 'How a lesson edit ships',
      caption:
        'Placeholder diagram from the ops desk docs. A clinician rules on a sentence, an agent claims the lesson and writes the edit, and a publish verifies it landed.',
      nodes: [
        {
          id: 'rule',
          label: 'Ruling',
          detail: 'A clinician marks a sentence',
          col: 0,
          row: 0,
          actor: 'person',
        },
        {
          id: 'queue',
          label: 'Queue',
          detail: 'The ask becomes a request',
          col: 1,
          row: 0,
          actor: 'system',
        },
        {
          id: 'claim',
          label: 'Claim',
          detail: 'An agent takes the lesson',
          col: 2,
          row: 0,
          actor: 'agent',
        },
        {
          id: 'edit',
          label: 'Edit + commit',
          detail: 'After text, then a trailer',
          col: 3,
          row: 0,
          actor: 'agent',
        },
        {
          id: 'publish',
          label: 'Publish',
          detail: 'Manifest and snapshots',
          col: 3,
          row: 1,
          actor: 'system',
        },
        {
          id: 'verify',
          label: 'Verify',
          detail: 'Old text gone, new text there',
          col: 2,
          row: 1,
          actor: 'system',
        },
        {
          id: 'confirm',
          label: 'Check the edit',
          detail: 'A person confirms the rest',
          col: 1,
          row: 1,
          actor: 'person',
        },
      ],
      edges: [
        ['rule', 'queue'],
        ['queue', 'claim'],
        ['claim', 'edit'],
        ['edit', 'publish'],
        ['publish', 'verify'],
        ['verify', 'confirm', 'unsure'],
      ],
    },
    'Placeholder: the start year is a guess, and the case study sections (architecture, the review loop, the video pipeline) are still to write.',
  ],
  role: ['co-founder', 'head engineer'],
  years: '2025–now',
  status: 'live',
  tech: [
    'TanStack Start',
    'React',
    'Cloudflare Workers',
    'D1',
    'R2',
    'Remotion',
  ],
  links: [{ label: 'berine.io', href: 'https://berine.io' }],
  media: { kind: 'none' },
  feature: 100,
}
